# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pharma-trace

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: appservice-pharma-trace
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.3'   # Alineado con Angular 20
          cache: 'npm'

      - name: Install deps and build (no tests)
        run: |
          npm ci
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_54B9A97308FA4C37B6BE0E6C5D9C0BCB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E50E3713E46545ECBCBA4F50FC2C8AAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_430951F863604E4DA6ACD7227953847E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pharma-trace'
          slot-name: 'Production'
          package: .
